apiVersion: v1
kind: Service
metadata:
  name: my-app-service-v2
spec:
  selector:
    app: my-app
    version: v2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  type: NodePort